FROM node:16-alpine

RUN mkdir /app && chown node:node /app

WORKDIR "/app"


COPY --chown=node:node package.json package-lock.json* ./

RUN npm install


RUN chown -R node /app/node_modules


COPY --chown=node:node . .

USER node

CMD [ "npm","run","start" ]