version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout

      # Install Dependencies (if needed)
      # - run: sudo apt-get update && sudo apt-get install ...

      - setup_remote_docker:
          docker_layer_caching: true

      - build_and_test:
          context: client
          dockerfile: Dockerfile.dev
      - run: docker run -e CI=true sudo1amir/react-test npm test

  build-and-push-images:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - build_and_push_images:
          filters:
            branches:
              only: main
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push sudo1amir/multi-container-react
      - run: docker push sudo1amir/multi-container-nginx
      - run: docker push sudo1amir/multi-container-server
      - run: docker push sudo1amir/multi-container-worker

  deploy:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - aws-elasticbeanstalk/deploy-application:
          app_name: my-docker-app
          env_name: My-docker-app-env
          region: us-east-1
          bucket_name: elasticbeanstalk-us-east-1-428846500808
          bucket_path: docker
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          deployment_policy: Rolling
          wait_for_completion: true

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - build-and-push-images:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-push-images
          filters:
            branches:
              only: main
