version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest  # Use an appropriate base image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Docker Test Image
          command: docker build -t sudo1amir/react-test -f ./client/Dockerfile.dev ./client/
      - run:
          name: Run Tests
          command: docker run -e CI=true sudo1amir/react-test npm test

  deploy-to-dockerhub:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Docker Images
          command: |
            docker build -t sudo1amir/multi-container-react ./client
            docker build -t sudo1amir/multi-container-nginx ./nginx
            docker build -t sudo1amir/multi-container-server ./server
            docker build -t sudo1amir/multi-container-worker ./worker
      - run:
          name: Push Images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push sudo1amir/multi-container-react
            docker push sudo1amir/multi-container-nginx
            docker push sudo1amir/multi-container-server
            docker push sudo1amir/multi-container-worker

  deploy-to-elasticbeanstalk:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm test
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade      
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            # Deploy using AWS Elastic Beanstalk CLI
            eb deploy My-docker-app-env

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy-to-dockerhub:
          requires:
            - build-and-test
      - deploy-to-elasticbeanstalk:
          requires:
            - deploy-to-dockerhub
          filters:
            branches:
              only: main
