version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/base:2023.04  # Use a CircleCI convenience image with Docker pre-installed

    steps:
      - checkout
      
      - setup_remote_docker:  # Set up Docker for remote execution

      - run:
          name: Build React test image
          command: docker build -t sudo1amir/react-test -f ./client/Dockerfile.dev ./client/

      - run:
          name: Run tests in React container
          command: docker run -e CI=true sudo1amir/react-test npm test

      - run:
          name: Build and push multi-container images
          command: |
            docker build -t sudo1amir/multi-container-react ./client
            docker build -t sudo1amir/multi-container-nginx ./nginx
            docker build -t sudo1amir/multi-container-server ./server
            docker build -t sudo1amir/multi-container-worker ./worker
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push sudo1amir/multi-container-react
            docker push sudo1amir/multi-container-nginx          
            docker push sudo1amir/multi-container-server
            docker push sudo1amir/multi-container-worker

      - deploy:
          name: Deploy to Elastic Beanstalk
          command: |
            # Install AWS CLI if needed
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            # Configure AWS credentials
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_KEY
            aws configure set default.region us-east-1

            # Deploy to Elastic Beanstalk (using AWS CLI commands)
            aws elasticbeanstalk create-application-version \
              --application-name my-docker-app \
              --version-label my-docker-app-version-$(date +%Y%m%d-%H%M%S) \
              --source-bundle S3Bucket=elasticbeanstalk-us-east-1-428846500808,S3Key=docker
            aws elasticbeanstalk update-environment \
              --environment-name My-docker-app-env \
              --version-label my-docker-app-version-$(date +%Y%m%d-%H%M%S)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: main
