version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout

      # Build Docker Image for Tests
      - run:
          name: Build Docker Test Image
          command: docker build -t sudo1amir/react-test -f ./client/Dockerfile.dev ./client/

      # Run Tests
      - run:
          name: Run Tests
          command: docker run -e CI=true sudo1amir/react-test npm test

      # Build Docker Images
      - run:
          name: Build Docker Images
          command: |
            docker build -t sudo1amir/multi-container-react ./client
            docker build -t sudo1amir/multi-container-nginx ./nginx
            docker build -t sudo1amir/multi-container-server ./server
            docker build -t sudo1amir/multi-container-worker ./worker

      # Push Images to Docker Hub
      - run:
          name: Push Images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push sudo1amir/multi-container-react
            docker push sudo1amir/multi-container-nginx          
            docker push sudo1amir/multi-container-server
            docker push sudo1amir/multi-container-worker

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            # Install AWS CLI
            sudo apt-get update && sudo apt-get install awscli
            # Deploy using Elastic Beanstalk CLI
            eb deploy My-docker-app-env --region us-east-1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main